// List fetched with this css selector from this wikipedia page
// https://en.wikipedia.org/wiki/List_of_districts_in_Bali
// $('table.wikitable:nth-child(n) > tbody:nth-child(2) > tr:nth-child(n) > td:nth-child(n) > div:nth-child(2) > ul:nth-child(1) > li:nth-child(n) > a:nth-child(1)')

export const locations = [
  'Angantaka, Abiansemal, Badung',
  'Ayunan, Abiansemal, Badung',
  'Blahkiuh, Abiansemal, Badung',
  'Bongkasa, Abiansemal, Badung',
  'Bongkasa Pertiwi, Abiansemal, Badung',
  'Darmasaba, Abiansemal, Badung',
  'Dauh Yeh Cani, Abiansemal, Badung',
  'Jagapati, Abiansemal, Badung',
  'Mambal, Abiansemal, Badung',
  'Mekar Bhuana, Abiansemal, Badung',
  'Punggul, Abiansemal, Badung',
  'Sangeh, Abiansemal, Badung',
  'Sedang, Abiansemal, Badung',
  'Selat, Abiansemal, Badung',
  'Sibang Gede, Abiansemal, Badung',
  'Sibang Kaja, Abiansemal, Badung',
  'Taman, Abiansemal, Badung',
  'Kedonganan, Kuta, Badung',
  'Tuban',
  'Kuta, Bali',
  'Legian',
  'Seminyak, Kuta, Badung',
  'Pecatu, South Kuta, Badung',
  'Ungasan, South Kuta, Badung',
  'Kutuh, South Kuta, Badung',
  'Benoa, South Kuta, Badung',
  'Tanjung Benoa',
  'Jimbaran, South Kuta, Badung',
  'Canggu',
  'Dalung, North Kuta, Badung',
  'Tibubeneng, North Kuta, Badung',
  'Kerobokan, North Kuta, Badung',
  'Kerobokan Kelod, North Kuta, Badung',
  'Kerobokan Kaja, North Kuta, Badung',
  'Baha, Mengwi, Badung',
  'Buduk, Mengwi, Badung',
  'Cemagi, Mengwi, Badung',
  'Gulingan, Mengwi, Badung',
  'Kekeran, Mengwi, Badung',
  'Kuwum, Mengwi, Badung',
  'Mengwi, Mengwi, Badung',
  'Mengwitani, Mengwi, Badung',
  'Munggu, Mengwi, Badung',
  'Penarungan, Mengwi, Badung',
  'Pererenan, Mengwi, Badung',
  'Sembung, Mengwi, Badung',
  'Sobangan, Mengwi, Badung',
  'Tumbak Bayuh, Mengwi, Badung',
  'Werdi Bhuwana, Mengwi, Badung',
  'Abianbase, Mengwi, Badung',
  'Kapal, Mengwi, Badung',
  'Lukluk, Mengwi, Badung',
  'Sading, Mengwi, Badung',
  'Sempidi, Mengwi, Badung',
  'Belok, Petang, Badung',
  'Carangsari, Petang, Badung',
  'Getasan, Petang, Badung',
  'Pangsan, Petang, Badung',
  'Pelaga, Petang, Badung',
  'Petang, Petang, Badung',
  'Sulangai, Petang, Badung',
  'Bunutin, Bangli, Bangli',
  'Kayubihi, Bangli, Bangli',
  'Landih, Bangli, Bangli',
  'Pengotan, Bangli, Bangli',
  'Taman Bali, Bangli, Bangli',
  'Bebalang, Bangli, Bangli',
  'Cempaga, Bangli, Bangli',
  'Kawan, Bangli, Bangli',
  'Kubu, Bangli, Bangli',
  'Abangsongan, Kintamani, Bangli',
  'Abuan, Kintamani, Bangli',
  'Awan, Kintamani, Bangli',
  'Bantang, Kintamani, Bangli',
  'Banua, Kintamani, Bangli',
  'Batudinding, Kintamani, Bangli',
  'Batukaang, Kintamani, Bangli',
  'Batur Selatan, Kintamani, Bangli',
  'Batur Tengah, Kintamani, Bangli',
  'Batur Utara, Kintamani, Bangli',
  'Bayungcerik, Kintamani, Bangli',
  'Bayung Gede, Kintamani, Bangli',
  'Belancan, Kintamani, Bangli',
  'Belandingan, Kintamani, Bangli',
  'Belanga, Kintamani, Bangli',
  'Belantih, Kintamani, Bangli',
  'Binyan, Kintamani, Bangli',
  'Bonyoh, Kintamani, Bangli',
  'Buahan, Kintamani, Bangli',
  'Bunutin, Kintamani, Bangli',
  'Catur, Kintamani, Bangli',
  'Daup, Kintamani, Bangli',
  'Dausa, Kintamani, Bangli',
  'Gunungbau, Kintamani, Bangli',
  'Katung, Kintamani, Bangli',
  'Kedisan, Kintamani, Bangli',
  'Kintamani, Kintamani, Bangli',
  'Kutuh, Kintamani, Bangli',
  'Langgahan, Kintamani, Bangli',
  'Lembean, Kintamani, Bangli',
  'Mangguh, Kintamani, Bangli',
  'Manikliyu, Kintamani, Bangli',
  'Mengani, Kintamani, Bangli',
  'Pengejaran, Kintamani, Bangli',
  'Pinggan, Kintamani, Bangli',
  'Satra, Kintamani, Bangli',
  'Sekaan, Kintamani, Bangli',
  'Sekardadi, Kintamani, Bangli',
  'Selulung, Kintamani, Bangli',
  'Serai, Kintamani, Bangli',
  'Siakin, Kintamani, Bangli',
  'Songan A, Kintamani, Bangli',
  'Songan B, Kintamani, Bangli',
  'Subaya, Kintamani, Bangli',
  'Sukawana, Kintamani, Bangli',
  'Suter, Kintamani, Bangli',
  'Terunyan, Kintamani, Bangli',
  'Ulian, Kintamani, Bangli',
  'Abuan, Susut, Bangli',
  'Apuan, Susut, Bangli',
  'Demulih, Susut, Bangli',
  'Pengiangan, Susut, Bangli',
  'Penglumbaran, Susut, Bangli',
  'Selat, Susut, Bangli',
  'Sulahan, Susut, Bangli',
  'Susut, Susut, Bangli',
  'Tiga, Susut, Bangli',
  'Bangbang, Tembuku, Bangli',
  'Jehem, Tembuku, Bangli',
  'Peninjoan, Tembuku, Bangli',
  'Tembuku, Tembuku, Bangli',
  'Undisan, Tembuku, Bangli',
  'Yangapi, Tembuku, Bangli',
  'Banjar, Banjar, Buleleng',
  'Banjar Tegeha, Banjar, Buleleng',
  'Banyuatis, Banjar, Buleleng',
  'Banyuseri, Banjar, Buleleng',
  'Cempaga, Banjar, Buleleng',
  'Dencarik, Banjar, Buleleng',
  'Gesing, Banjar, Buleleng',
  'Gobleg, Banjar, Buleleng',
  'Kaliasem, Banjar, Buleleng',
  'Kayuputih, Banjar, Buleleng',
  'Munduk, Banjar, Buleleng',
  'Pedawa, Banjar, Buleleng',
  'Sidetapa, Banjar, Buleleng',
  'Tampekan, Banjar, Buleleng',
  'Temukus, Banjar, Buleleng',
  'Tigawasa, Banjar, Buleleng',
  'Tirtasari, Banjar, Buleleng',
  'Alasangker, Buleleng, Buleleng',
  'Anturan, Buleleng, Buleleng',
  'Bakti Seraga, Buleleng, Buleleng',
  'Jinengdalem, Buleleng, Buleleng',
  'Kalibukbuk, Buleleng, Buleleng',
  'Nagasepaha, Buleleng, Buleleng',
  'Pemaron, Buleleng, Buleleng',
  'Penglatan, Buleleng, Buleleng',
  'Petandakan, Buleleng, Buleleng',
  'Poh Bergong, Buleleng, Buleleng',
  'Sari Mekar, Buleleng, Buleleng',
  'Tukadmungga, Buleleng, Buleleng',
  'Astina, Buleleng, Buleleng',
  'Banjar Bali, Buleleng, Buleleng',
  'Banjar Jawa, Buleleng, Buleleng',
  'Banjar Tegal, Buleleng, Buleleng',
  'Banyuasri, Buleleng, Buleleng',
  'Banyuning, Buleleng, Buleleng',
  'Beratan, Buleleng, Buleleng',
  'Kaliuntu, Buleleng, Buleleng',
  'Kampung Anyar, Buleleng, Buleleng',
  'Kampung Baru, Buleleng, Buleleng',
  'Kampung Bugis, Buleleng, Buleleng',
  'Kampung Kajanan, Buleleng, Buleleng',
  'Kampung Singaraja, Buleleng, Buleleng',
  'Kendran, Buleleng, Buleleng',
  'Liligundi, Buleleng, Buleleng',
  'Paket Agung, Buleleng, Buleleng',
  'Penarukan, Buleleng, Buleleng',
  'Bengkel, Busung Biu, Buleleng',
  'Bongancina, Busung Biu, Buleleng',
  'Busung Biu, Busung Biu, Buleleng',
  'Kedis, Busung Biu, Buleleng',
  'Kekeran, Busung Biu, Buleleng',
  'Pelapuan, Busung Biu, Buleleng',
  'Pucaksari, Busung Biu, Buleleng',
  'Sepang, Busung Biu, Buleleng',
  'Sepang Kelod, Busung Biu, Buleleng',
  'Subuk, Busung Biu, Buleleng',
  'Telaga, Busung Biu, Buleleng',
  'Tinggarsari, Busung Biu, Buleleng',
  'Tista, Busung Biu, Buleleng',
  'Titab, Busung Biu, Buleleng',
  'Umejero, Busung Biu, Buleleng',
  'Banyupoh, Gerokgak, Buleleng',
  'Celukanbawang, Gerokgak, Buleleng',
  'Gerokgak, Gerokgak, Buleleng',
  'Musi, Gerokgak, Buleleng',
  'Patas, Gerokgak, Buleleng',
  'Pejarakan, Gerokgak, Buleleng',
  'Pemuteran, Gerokgak, Buleleng',
  'Pengulon, Gerokgak, Buleleng',
  'Penyabangan, Gerokgak, Buleleng',
  'Sanggalangit, Gerokgak, Buleleng',
  'Sumberklampok, Gerokgak, Buleleng',
  'Sumberkima',
  'Tinga-Tinga, Gerokgak, Buleleng',
  'Tukadsumaga, Gerokgak, Buleleng',
  'Bengkala, Kubutambahan, Buleleng',
  'Bila, Kubutambahan, Buleleng',
  'Bontihing, Kubutambahan, Buleleng',
  'Bukti, Kubutambahan, Buleleng',
  'Bulian, Kubutambahan, Buleleng',
  'Depeha, Kubutambahan, Buleleng',
  'Kubutambahan, Kubutambahan, Buleleng',
  'Mengening, Kubutambahan, Buleleng',
  'Pakisan, Kubutambahan, Buleleng',
  'Tajun, Kubutambahan, Buleleng',
  'Tambakan, Kubutambahan, Buleleng',
  'Tamblang, Kubutambahan, Buleleng',
  'Tunjung, Kubutambahan, Buleleng',
  'Bebetin, Sawan, Buleleng',
  'Bungkulan, Sawan, Buleleng',
  'Galungan, Sawan, Buleleng',
  'Giri Emas, Sawan, Buleleng',
  'Jagaraga, Sawan, Buleleng',
  'Kerobokan, Sawan, Buleleng',
  'Lemukih, Sawan, Buleleng',
  'Menyali, Sawan, Buleleng',
  'Sangsit, Sawan, Buleleng',
  'Sawan, Sawan, Buleleng',
  'Sekumpul, Sawan, Buleleng',
  'Sinabun, Sawan, Buleleng',
  'Sudaji, Sawan, Buleleng',
  'Suwug, Sawan, Buleleng',
  'Banjar Asem, Seririt, Buleleng',
  'Bestala, Seririt, Buleleng',
  'Bubunan, Seririt, Buleleng',
  'Gunungsari, Seririt, Buleleng',
  'Joanyar, Seririt, Buleleng',
  'Kalianget, Seririt, Buleleng',
  'Kalisada, Seririt, Buleleng',
  'Lokapaksa, Seririt, Buleleng',
  'Mayong, Seririt, Buleleng',
  'Munduk Bestala, Seririt, Buleleng',
  'Pangkung Paruk, Seririt, Buleleng',
  'Patemon, Seririt, Buleleng',
  'Pengastulan, Seririt, Buleleng',
  'Rangdu, Seririt, Buleleng',
  'Ringdikit, Seririt, Buleleng',
  'Sulanyah, Seririt, Buleleng',
  'Tangguwisia, Seririt, Buleleng',
  'Ularan, Seririt, Buleleng',
  'Umeanyar, Seririt, Buleleng',
  'Unggahan, Seririt, Buleleng',
  'Seririt, Seririt, Buleleng',
  'Ambengan, Sukasada, Buleleng',
  'Git Git, Sukasada, Buleleng',
  'Kayu Putih, Sukasada, Buleleng',
  'Padang Bulia, Sukasada, Buleleng',
  'Pancasari, Sukasada, Buleleng',
  'Panji, Sukasada, Buleleng',
  'Panji Anom, Sukasada, Buleleng',
  'Pegadungan, Sukasada, Buleleng',
  'Pegayaman, Sukasada, Buleleng',
  'Sambangan, Sukasada, Buleleng',
  'Selat, Sukasada, Buleleng',
  'Silangjana, Sukasada, Buleleng',
  'Tegal Linggah, Sukasada, Buleleng',
  'Wanagiri, Sukasada, Buleleng',
  'Sukasada, Sukasada, Buleleng',
  'Bondalem, Tejakula, Buleleng',
  'Julah, Tejakula, Buleleng',
  'Les, Tejakula, Buleleng',
  'Madenan, Tejakula, Buleleng',
  'Pacung, Tejakula, Buleleng',
  'Penuktukan, Tejakula, Buleleng',
  'Sambirenteng, Tejakula, Buleleng',
  'Sembiran, Tejakula, Buleleng',
  'Tejakula, Tejakula, Buleleng',
  'Tembok, Tejakula, Buleleng',
  'Bedulu, Blahbatuh, Gianyar',
  'Belega, Blahbatuh, Gianyar',
  'Blahbatuh, Blahbatuh, Gianyar',
  'Bona, Blahbatuh, Gianyar',
  'Buruan, Blahbatuh, Gianyar',
  'Keramas, Blahbatuh, Gianyar',
  'Medahan, Blahbatuh, Gianyar',
  'Pering, Blahbatuh, Gianyar',
  'Saba, Blahbatuh, Gianyar',
  'Bakbakan, Gianyar',
  'Lebih, Gianyar, Gianyar',
  'Petak, Gianyar, Gianyar',
  'Petak Kaja, Gianyar, Gianyar',
  'Serongga, Gianyar, Gianyar',
  'Siangan, Gianyar, Gianyar',
  'Sidan, Gianyar, Gianyar',
  'Sumita, Gianyar, Gianyar',
  'Suwat, Gianyar, Gianyar',
  'Tegal Tugu, Gianyar, Gianyar',
  'Temesi, Gianyar, Gianyar',
  'Tulikup, Gianyar, Gianyar',
  'Abianbase, Gianyar, Gianyar',
  'Beng, Gianyar, Gianyar',
  'Bitera, Gianyar, Gianyar',
  'Gianyar, Gianyar, Gianyar',
  'Samplangan, Gianyar, Gianyar',
  'Bresela, Payangan, Gianyar',
  'Buahan, Payangan, Gianyar',
  'Buahan Kaja, Payangan, Gianyar',
  'Bukian, Payangan, Gianyar',
  'Kelusa, Payangan, Gianyar',
  'Kerta, Payangan, Gianyar',
  'Melinggih, Payangan, Gianyar',
  'Melinggih Kelod, Payangan, Gianyar',
  'Puhu, Payangan, Gianyar',
  'Batuan, Sukawati, Gianyar',
  'Batuan Kaler, Sukawati, Gianyar',
  'Batubulan, Sukawati, Gianyar',
  'Batubulan Kangin, Sukawati, Gianyar',
  'Celuk, Sukawati, Gianyar',
  'Guwang, Sukawati, Gianyar',
  'Kemenuh, Sukawati, Gianyar',
  'Ketewel, Sukawati, Gianyar',
  'Singapadu, Sukawati, Gianyar',
  'Singapadu Kaler, Sukawati, Gianyar',
  'Singapadu Tengah, Sukawati, Gianyar',
  'Sukawati, Sukawati, Gianyar',
  'Manukaya, Tampaksiring, Gianyar',
  'Pejeng, Tampaksiring, Gianyar',
  'Pejeng Kaja, Tampaksiring, Gianyar',
  'Pejeng Kangin, Tampaksiring, Gianyar',
  'Pejeng Kawan, Tampaksiring, Gianyar',
  'Pejeng Kelod, Tampaksiring, Gianyar',
  'Sanding, Tampaksiring, Gianyar',
  'Tampaksiring, Tampaksiring, Gianyar',
  'Kedisan, Tegallalang, Gianyar',
  'Keliki, Tegallalang, Gianyar',
  'Kendran, Tegallalang, Gianyar',
  'Pupuan, Tegallalang, Gianyar',
  'Sebatu, Tegallalang, Gianyar',
  'Taro, Tegallalang, Gianyar',
  'Tegallalang, Tegallalang, Gianyar',
  'Kedewatan, Ubud, Gianyar',
  'Lodtunduh, Ubud, Gianyar',
  'Mas, Ubud, Gianyar',
  'Peliatan, Ubud, Gianyar',
  'Petulu, Ubud, Gianyar',
  'Sayan, Ubud, Gianyar',
  'Singakerta, Ubud, Gianyar',
  'Ubud, Ubud, Gianyar',
  'Dauh Puri Kangin, West Denpasar, Denpasar',
  'Dauh Puri Kauh, West Denpasar, Denpasar',
  'Dauh Puri Klod, West Denpasar, Denpasar',
  'Padang Sambian Kaja, West Denpasar, Denpasar',
  'Padang Sambian Klod, West Denpasar, Denpasar',
  'Pemecutan Klod, West Denpasar, Denpasar',
  'Tegal Harum, West Denpasar, Denpasar',
  'Tegal Kerta, West Denpasar, Denpasar',
  'Dauh Puri, West Denpasar, Denpasar',
  'Padang Sambian, West Denpasar, Denpasar',
  'Pemecutan, West Denpasar, Denpasar',
  'Pemogan, South Denpasar, Denpasar',
  'Sanur Kaja, South Denpasar, Denpasar',
  'Sanur Kauh, South Denpasar, Denpasar',
  'Sidakarya, South Denpasar, Denpasar',
  'Panjer, South Denpasar, Denpasar',
  'Pedungan, South Denpasar, Denpasar',
  'Renon, South Denpasar, Denpasar',
  'Sanur, South Denpasar, Denpasar',
  'Serangan, South Denpasar, Denpasar',
  'Sesetan, South Denpasar, Denpasar',
  'Dangin Puri Klod, East Denpasar, Denpasar',
  'Kesiman Kertalangu, East Denpasar, Denpasar',
  'Kesiman Petilan, East Denpasar, Denpasar',
  'Penatih Dangin Puri, East Denpasar, Denpasar',
  'Sumerta Kaja, East Denpasar, Denpasar',
  'Sumerta Kauh, East Denpasar, Denpasar',
  'Sumerta Klod/Kelod, East Denpasar, Denpasar',
  'Dangin Puri, East Denpasar, Denpasar',
  'Kesiman, East Denpasar, Denpasar',
  'Penatih, East Denpasar, Denpasar',
  'Sumerta, East Denpasar, Denpasar',
  'Dangin Puri Kaja, North Denpasar, Denpasar',
  'Dangin Puri Kangin, North Denpasar, Denpasar',
  'Dangin Puri Kauh, North Denpasar, Denpasar',
  'Dauh Puri Kaja, North Denpasar, Denpasar',
  'Peguyangan Kaja, North Denpasar, Denpasar',
  'Peguyangan Kangin, North Denpasar, Denpasar',
  'Pemecutan Kaja, North Denpasar, Denpasar',
  'Ubung Kaja, North Denpasar, Denpasar',
  'Peguyangan, North Denpasar, Denpasar',
  'Tonja, North Denpasar, Denpasar',
  'Ubung, North Denpasar, Denpasar',
]
